version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:22"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=172.17.52.21
      - DB_PORT=3306
      - DB_DATABASE=SIGNATURE_DIGITAL
      - DB_USERNAME=formia
      - DB_PASSWORD=qwe123123
